server:
  port: 8083

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: RAGHUL
    password: 6379362346
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history_account_service
    out-of-order: true
    clean-disabled: false
    baseline-version: 0
    baseline-description: "Initial baseline for Account Service"

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: account-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.bank.account.dto,com.bank.kyc.events"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: account-events

jwt:
  secret: bXlfc3VwZXJfc2VjdXJlX3Rlc3Rfa2V5XzEyMzQ1Njc4OTA=
  expiration-ms: 3600000

services:
  customer:
    base-url: http://localhost:8081
  kyc:
    base-url: http://localhost:8084
  gateway:
    base-url: http://localhost:8080

account:
  number:
    prefix: BANK
    savings-code: SAV
    current-code: CUR
  default-balance:
    savings: 1000.00
    current: 5000.00

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    display-request-duration: true
    doc-expansion: none
    deep-linking: true
  info:
    title: Account Service API
    description: REST API documentation for the Account Service in the Secure Onboarding Banking System.
    version: 1.0.0
    termsOfService: https://yourbank.com/terms
    contact:
      name: API Support
      url: https://yourbank.com/support
      email: support@yourbank.com
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    com.bank.account: DEBUG
